theme: jekyll-theme-minimal
title: Mike Stevens
tile_image: /assets/images/2018_misteven_500px.png
description: stuff and things
logo: /assets/images/cloud.png
show_downloads: true
blog: https://mike11stevens.com
twitter_username: "@mike11stevens"
twitter: https://twitter.com/@mike11stevens
permalink:  /blog/:year/:month/:day/:title
paginate: 10
plugins:
  - jekyll-sitemap